version: '3.7'

services:
  videoportal:
    restart: unless-stopped
    volumes:
      - ./static:/static
      - ./sqlite-data:/app/db
    build: 
      context: .

  # Needed for static files
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "21000:80"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./static:/static
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - videoportal

volumes:
  caddy_data:
  caddy_config:
